---
kind: pipeline
name: test-build

platform:
  os: linux
  arch: amd64 # Docker buildx will build for all target architectures.

steps:
  - name: build-multi-arch-image
    image: thegeeklab/drone-docker-buildx:23.0.1
    privileged: true # Needs access to docker socket for buildx.
    settings:
      platforms:
        - linux/amd64
        - linux/arm64

    when:
      event:
        exclude:
        - tag
