project_name: goreleaser
builds:
- skip: true
source:
  rlcp: true
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_source_code'
sboms:
  # Generate SBOM for all source files.
  - id: source
    artifacts: source
    documents:
      - '{{ .ProjectName }}_{{ .Version }}_source.spdx.json'
  # Generate SBOM for all layers of the container image.
  - artifacts: any
    args: [
      "{{ .Env.REPO }}:{{ .Env.DRONE_TAG }}", 
      "--file", "{{ .ProjectName }}_{{ .Version }}_image.spdx.json", "--scope", "all-layers", "--output", "spdx-json"]
    documents:
      - '{{ .ProjectName }}_{{ .Version }}_image.spdx.json'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true
