name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions: 
  contents: write
  packages: write
  id-token: write

env: 
  REPO: ghcr.io/pjbgf/goreleaser

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0.13.3
      - name: Setup Cosign
        uses: sigstore/cosign-installer@v2.8.1
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: git fetch --force --tags
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
